name:'从python应用程序构建'
on:[push]
jobs:
  build:
    runs-on:windows-latest
    steps:
      - uses:actions/checkout@v2
      - name:设置Python 3.8
        uses:actions/setup-python@v1
        with:
          python-version:3.8
      - name:安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name:运行测试
        run: |
          pip install pytest
          pytest
      - name:构建应用程序
        run: |
          pip install pyinstaller
          pyinstaller -F python/login.py