name: 'Build_python_exe'
on: [push]
name: 'Build_python_exe'
on: [push]
jobs:
  build:
    runs-on: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
          pip install pyinstaller
      - name: Build exe
        run: |
          pyinstaller -F python/login.py
